# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '内容',
                'db_table': 'p_content',
                'verbose_name': '内容',
            },
        ),
    ]
